### ISSUE TITLE
Getting an error on certain rsrc files

### ISSUE THREAD

**Issue by badmotorfinger** [jorio/rsrcdump#4]
I am trying to extract resources and getting this error. Files attached for reference. Any help would be appreciated.

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/vince/sourcecode/repos-macintosh/TheMacAttic/rsrc/rsrcdump/__main__.py", line 75, in <module>
    extract_resource_map(res_map, outpath, include_types, exclude_types)
  File "/home/vince/sourcecode/repos-macintosh/TheMacAttic/rsrc/rsrcdump/extract.py", line 43, in extract_resource_map
    obj = converter.convert(res, res_map)
  File "/home/vince/sourcecode/repos-macintosh/TheMacAttic/rsrc/rsrcdump/resconverters.py", line 96, in convert
    w, h, data = convert_pict_to_image(res.data)
  File "/home/vince/sourcecode/repos-macintosh/TheMacAttic/rsrc/rsrcdump/pict.py", line 466, in convert_pict_to_image
    raise PICTError(F"unsupported PICT opcode 0x{opcode:04x}")
rsrcdump.pict.PICTError: unsupported PICT opcode 0x009b
/tmp/1HjH4oj7fR/nwJ6BVurxr/Wo

[Iggy's Adventure 1.0.zip](https://github.com/jorio/rsrcdump/files/11176155/Iggy.s.Adventure.1.0.zip)
rld.rsrc

**Comment by jorio** [comment]
Thanks for reporting this. The PICT decoder was lacking support for the DirectBitsRgn opcode.

The latest version of rsrcdump should be able to convert the attached PICTs.

Note that the command-line interface has changed a bit since the previous public version. Extracting is now carried out with `rsrcdump.sh -x ....rsrc`. For all options try `rsrcdump.sh -h` or see the readme.

**Comment by badmotorfinger** [comment]
Working perfectly. Thank you so much.
